#!/bin/bash
# Gmail App Password Setup Guide

echo "🔧 GMAIL SETUP FOR AFELU GUARDIAN"
echo "================================="
echo ""
echo "1. Go to: https://myaccount.google.com/security"
echo "2. Enable 2-Step Verification (if not already enabled)"
echo "3. Click 'App passwords'"
echo "4. Select app: 'Mail'"
echo "5. Select device: 'Other (Custom name)'"
echo "6. Enter name: 'Afelu Guardian Platform'"
echo "7. Click 'Generate'"
echo "8. Copy the 16-character password (format: xxxx xxxx xxxx xxxx)"
echo ""
echo "Then run this command with your Gmail app password:"
echo ""
echo "railway variables --set \"SMTP_PASS=your_gmail_app_password_here\""
echo ""
echo "Example:"
echo "railway variables --set \"SMTP_PASS=abcd efgh ijkl mnop\""
echo ""
echo "🚀 Your Gmail is already configured in Railway:"
echo "   SMTP_HOST=smtp.gmail.com"
echo "   SMTP_USER=mybirdsounds@gmail.com"
echo "   FROM_EMAIL=mybirdsounds@gmail.com"
echo ""
echo "Just need to set the app password and test!"
